### PR TITLE
custom tool tip function

### PR DESCRIPTION
**Pull request by g-g-n**

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Hi! If I'm reading this right, it seems like this is just providing another way to change the text. Is that right? Or does it actually show a tooltip? Sorry for the delay!

**Comment by g-g-n** [comment]
A way for the user to provide a tooltip function. So he can control what he
wants to see/show in the tool tip.

Regards
GG

**Comment by paulmelnikow** [comment]
Ah, I got it now. Sorry, I hadn't looked at this code in a while. I'll tweak this a little bit, but it's something I'm happy to include.

**Comment by g-g-n** [comment]
Great. Thanks.

**Pull request merged**
