### PR TITLE
some handy optional attributes

### PR DESCRIPTION
**Pull request by j2kenton**
Hi,
Would you mind taking a look at my fork and letting me know if you are interested in a merge?
Cheers!
Jonathan

### CODE REVIEW

**Comment by paulmelnikow** [comment]
The indentation change is making a big diff. Do you think you could clean that up? It's hard to see what's been changed.

**Comment by j2kenton** [comment]
Hi Paul,
Sorry about the delay and the indentation mess-up.
Could you take a look at my new commit and let me know - all feedback welcome :)
Thanks for your patience!
Jonathan

**Comment by paulmelnikow** [comment]
Thanks!

**Comment by paulmelnikow** [comment]
Out of curiosity, how did you become interested in this project? It's always interesting to know how people are using the projects I've worked on.

**Comment by j2kenton** [comment]
[emailed you directly]

**Pull request merged**
